version: '3'

services:

  # HTTP API
  flask:
    build: .
    container_name: flask
    ports:
      - '5000:5000'
    depends_on:
      - redis

  # Поднимает очередь задач
  parser:
    build: ./service
    container_name: worker
    command: rq worker -u redis://redis:6379
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - '6379:6379'